CREATE DATABASE Session13
GO
USE Session13
GO
CREATE TABLE Test
(
	ID INT IDENTITY PRIMARY KEY,
	[Value] NVARCHAR(10),
	CreatedDate DATETIME DEFAULT GETDATE()
)
GO
UPDATE Test SET [Value] =
CONVERT(NVARCHAR(10), CONVERT(INT, RAND() * 10000))
WHERE ID = 4
GO 1000000
CREATE INDEX IX_Value ON Test([Value])
GO
INSERT INTO Test([Value]) VALUES(CONVERT(NVARCHAR(10), CONVERT(INT, RAND() * 10000000)))
GO 10000