CREATE DATABASE Session15
GO
USE Session15
GO
CREATE TABLE Tbl1 
(
	Id INT IDENTITY PRIMARY KEY,
	[Value] NVARCHAR(10)
)
GO
CREATE TABLE Tbl2
(
	Id INT IDENTITY PRIMARY KEY,
	[Value] NVARCHAR(10)
) ON LargeDataFileGroup
GO
INSERT INTO Tbl1 VALUES (CONVERT(NVARCHAR(10),RAND()*100000))
GO 100000
INSERT INTO Tbl2 VALUES (CONVERT(NVARCHAR(10),RAND()*100000))
GO 100000
DROP TABLE Attachments
GO
CREATE TABLE Attachments
(
	Id INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(50),
	AttachmentFile VARBINARY(MAX) FILESTREAM,
	RowGuid UNIQUEIDENTIFIER ROWGUIDCOL UNIQUE NOT NULL DEFAULT NEWID()
)
GO
DECLARE @file AS VARBINARY(MAX)
-- Load the image data
SELECT @file = CAST(bulkcolumn AS VARBINARY(MAX))
      FROM OPENROWSET(
            BULK
            'D:\Angular.pdf',
            SINGLE_BLOB ) AS x
INSERT INTO Attachments(Name, AttachmentFile)
VALUES ('Angular.pdf', @file)
GO
SELECT * FROM Attachments
GO
EXEC sp_configure filestream_access_level, 2  
RECONFIGURE  
GO
DBCC CHECKDB
GO
DBCC CHECKTABLE ('Attachments')
GO
DBCC CHECKTABLE ('Tbl1')
GO
DBCC CHECKIDENT ('Tbl1')
GO
DBCC CHECKCONSTRAINTS ('Tbl1')
GO
GO
BULK INSERT PhoneBook FROM 'D:\data.csv'
   WITH (
      FIELDTERMINATOR = ',',
      ROWTERMINATOR = '\n'
);
GO
